spring:
  application:
    name: ms-pedidos360-audit

  r2dbc:
    url: r2dbc:postgresql://localhost:5432/ms-audit?scheme=audit
    username: ${DB-USER:postgres}
    password: ${DB-PASSWORD:root}

  flyway:
    url: jdbc:postgresql://localhost:5432/ms-audit
    user: ${spring.r2dbc.username}
    password: ${spring.r2dbc.password}
    locations: classpath:db/migration
    baseline-on-migrate: true
    default-schema: audit

  output:
    ansi:
      enabled: always

logging:
  level:
    org:
      springframework:
        r2dbc: DEBUG

server:
  port: 8085
