spring:
  application:
    name: ms-pedidos360-order

  r2dbc:
    url: r2dbc:${DB_URL:postgresql://localhost:5432/ms-orders?scheme=orders}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:root}

  flyway:
    url: jdbc:${DB_URL:postgresql://localhost:5432/ms-orders}
    password: ${DB_PASSWORD:root}
    user: ${DB_USER:postgres}
    locations: classpath:db/migration
    baseline-on-migrate: true
    default-schema: orders

  output:
    ansi:
      enabled: always

server:
  port: 8081

logging:
  level:
    org:
      springframework:
        r2dbc: DEBUG

