spring:
  application:
    name: ms-pedidos360-report
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/ms-reports?search_path=reports
    username: ${DB-USER:postgres}
    password: ${DB-PASSWORD:root}

  flyway:
    url: jdbc:postgresql://localhost:5432/ms-reports
    user: ${spring.r2dbc.username}
    password: ${spring.r2dbc.password}
    locations: classpath:db/migration
    baseline-on-migrate: true
    default-schema: reports

  output:
    ansi:
      enabled: always

server:
  port: 8084

logging:
  level:
    org:
      springframework:
        r2dbc: DEBUG
